'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Apprentissage.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf56() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf56", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf561() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf561", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf562() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf562", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf563() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf563", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf564() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf564", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf565() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf565", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf566() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf566", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf567() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf567", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf568() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf568", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf569() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf569", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf57() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf57", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf571() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf571", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf5711() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf5711", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf572() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf572", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf573() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf573", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf574() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf574", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf575() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf575", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf576() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf576", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf577() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf577", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf578() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf578", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf579() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf579", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf580() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf580", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf581() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf581", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf582() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf582", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf583() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf583", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf584() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf584", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9cf043a337c01af7db6b3ee63456cf585() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9cf043a337c01af7db6b3ee63456cf585", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ananas_en_couleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ananas-en-couleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ananas_en_couleur1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ananas-en-couleur1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property étude_de_la_banane_découverte_lettres_d_alphabet_traçant_feuille_calcul_pour_les_enfants_exercice_à_l_école_primaire_189569567() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("étude-de-la-banane-découverte-lettres-d-alphabet-traçant-feuille-calcul-pour-les-"& _ 
                        "enfants-exercice-à-l-école-primaire-189569567", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
